### ISSUE TITLE
iFrame Communication

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-theme#2]
Integrate [seamless.js](https://github.com/travist/seamless.js) in default theme to support bi-directional iFrame Communication with [Drupal Site](https://github.com/clarity-h2020/docker-drupal). See also https://github.com/clarity-h2020/scenario-analysis/issues/2

**Comment by p-a-s-c-a-l** [comment]
@fgeyer16 @patrickkaleta 

Adding the JS File to the theme following [this guide](https://www.appnovation.com/blog/how-add-js-and-css-assets-drupal-8-theme) doesn't seem to work even after rebuilding the cache with ``drush cr``.

Can you please check the yaml fines in [branch 02-seamless-js](https://github.com/clarity-h2020/csis-theme/tree/feature/02-seamless-js) for errors? 

The [official documentation](https://www.drupal.org/docs/8/api/javascript-api/add-javascript-to-your-theme-or-module) is not very clear about how and where to enable those libraries defined in csis.libraries.yaml.

**Comment by p-a-s-c-a-l** [comment]
```yaml
global-scripts:
  version: 0.1
  header: true
  js:
    js/seamless.parent.js: {preprocess: false}
    js/csis.js: {}
```

Doesn't seem to work either.
